const scholarships = [
  {
    id: 1,
    title: "MIT Need-Based Scholarship",
    org: "Massachusetts Institute of Technology",
    country: "USA",
    level: "undergraduate",
    field: "Any",
    funding: "Full",
    amount: "Up to $75,000/yr",
    deadline: "Jan 1, 2027",
    urgent: false,
    link: "https://mitadmissions.org/afford/",
    description: "MIT meets 100% of demonstrated financial need for all admitted students. No loans required."
  },
  {
    id: 2,
    title: "Mastercard Foundation Scholars Program",
    org: "Various African Universities",
    country: "Nigeria",
    level: "undergraduate",
    field: "Any",
    funding: "Full",
    amount: "Full tuition + stipend",
    deadline: "Dec 1, 2026",
    urgent: false,
    link: "https://mastercardfdn.org/",
    description: "Full scholarships for academically talented yet economically disadvantaged African students."
  },
  {
    id: 3,
    title: "Commonwealth Scholarship",
    org: "Commonwealth Scholarship Commission",
    country: "UK",
    level: "postgraduate",
    field: "Any",
    funding: "Full",
    amount: "Full tuition + living allowance",
    deadline: "Oct 15, 2026",
    urgent: false,
    link: "https://cscuk.fcdo.gov.uk/",
    description: "For Nigerian students to study masters or PhD programmes in the UK."
  },
  {
    id: 4,
    title: "Chevening Scholarship",
    org: "UK Foreign Commonwealth & Development Office",
    country: "UK",
    level: "postgraduate",
    field: "Any",
    funding: "Full",
    amount: "Full masters funding",
    deadline: "Nov 5, 2026",
    urgent: false,
    link: "https://www.chevening.org/",
    description: "UK government's flagship scholarship for future leaders worldwide. Fully funded masters."
  },
  {
    id: 5,
    title: "NNPC/SNEPCo National University Scholarship",
    org: "NNPC & SNEPCo",
    country: "Nigeria",
    level: "undergraduate",
    field: "STEM",
    funding: "Full",
    amount: "₦200,000/yr + mentorship",
    deadline: "Jul 30, 2026",
    urgent: true,
    link: "https://www.snepco.com/",
    description: "For top Nigerian students studying STEM disciplines in Nigerian universities."
  },
  {
    id: 6,
    title: "Fulbright Foreign Student Program",
    org: "US Department of State",
    country: "USA",
    level: "postgraduate",
    field: "Any",
    funding: "Full",
    amount: "Full tuition + living costs",
    deadline: "Mar 1, 2027",
    urgent: false,
    link: "https://foreign.fulbrightonline.org/",
    description: "Prestigious US government scholarship for postgraduate study in America. Fully funded."
  },
  {
    id: 7,
    title: "MTN Foundation Scholarship",
    org: "MTN Nigeria Foundation",
    country: "Nigeria",
    level: "undergraduate",
    field: "STEM",
    funding: "Partial",
    amount: "₦150,000/yr",
    deadline: "Aug 15, 2026",
    urgent: true,
    link: "https://mtnfoundation.com/",
    description: "For Nigerian students studying science and technology fields in Nigerian universities."
  },
  {
    id: 8,
    title: "DAAD Scholarship",
    org: "German Academic Exchange Service",
    country: "Global",
    level: "postgraduate",
    field: "Any",
    funding: "Full",
    amount: "Full tuition + €934/month",
    deadline: "Oct 1, 2026",
    urgent: false,
    link: "https://www.daad.de/",
    description: "Study in Germany fully funded. Open to Nigerian postgraduate students in all fields."
  },
  {
    id: 9,
    title: "TETFund Scholarship",
    org: "Tertiary Education Trust Fund",
    country: "Nigeria",
    level: "postgraduate",
    field: "Any",
    funding: "Full",
    amount: "Full funding",
    deadline: "Ongoing",
    urgent: false,
    link: "https://tetfund.gov.ng/",
    description: "Nigerian government scholarship for academic staff development and postgraduate studies."
  },
  {
    id: 10,
    title: "Harvard Griffin GSAS Fellowship",
    org: "Harvard University",
    country: "USA",
    level: "postgraduate",
    field: "Any",
    funding: "Full",
    amount: "Full PhD funding + stipend",
    deadline: "Dec 15, 2026",
    urgent: false,
    link: "https://gsas.harvard.edu/",
    description: "Harvard PhD programs are fully funded with generous stipends for all admitted students."
  },
  {
    id: 11,
    title: "Canadian Commonwealth Scholarship",
    org: "Government of Canada",
    country: "Canada",
    level: "postgraduate",
    field: "Any",
    funding: "Full",
    amount: "Full tuition + CAD $1,500/month",
    deadline: "Feb 1, 2027",
    urgent: false,
    link: "https://www.canada.ca/en/global-affairs/",
    description: "Full funding for Nigerian postgraduate students to study in Canada."
  },
  {
    id: 12,
    title: "Shell Nigeria Scholarship",
    org: "Shell Petroleum Development Company",
    country: "Nigeria",
    level: "undergraduate",
    field: "STEM",
    funding: "Partial",
    amount: "₦500,000/yr",
    deadline: "Jun 30, 2026",
    urgent: true,
    link: "https://www.shell.com.ng/",
    description: "For top Nigerian students studying engineering and sciences in Nigerian universities."
  }
];
